### ISSUE TITLE
Failed to lookup telemetry handlers

### ISSUE THREAD

**Issue by zacky1972** [zacky1972/ex_task#18]
I did the following steps:

1. ` mix new test`
2. `cd test`
3.  Add `{:ex_task, "~> 0.1", runtime: false}` to `deps` in `mix.exs`
4. Add `compilers: [:ex_task] ++ Mix.compilers,` to `project` in `mix.exs`
5. `mix deps.get`

Then the following error occurred:

```elixir
==> ex_task
Compiling 2 files (.ex)
Generated ex_task app

13:23:44.937 [warning] Failed to lookup telemetry handlers. Ensure the telemetry application has been started. 

13:23:44.939 [warning] Failed to lookup telemetry handlers. Ensure the telemetry application has been started. 
** (ArgumentError) unknown registry: Req.Finch
    (elixir 1.17.2) lib/registry.ex:1400: Registry.key_info!/1
    (elixir 1.17.2) lib/registry.ex:590: Registry.lookup/2
    (finch 0.19.0) lib/finch/pool_manager.ex:50: Finch.PoolManager.lookup_pool/2
    (finch 0.19.0) lib/finch/pool_manager.ex:38: Finch.PoolManager.get_pool/3
    (finch 0.19.0) lib/finch.ex:449: Finch.__stream__/5
    (finch 0.19.0) lib/finch.ex:493: anonymous fn/4 in Finch.request/3
    (telemetry 1.3.0) /Users/zacky/test/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
    (req 0.5.6) lib/req/finch.ex:239: Req.Finch.run_finch_request/3
```

**Comment by zacky1972** [comment]
Perhaps, the following tip is useful to fix this issue:

https://elixirforum.com/t/argumenterror-unknown-registry-req-finch-on-a-simple-http-request-using-req-library/64638/2

> Oh, you’re using Req at compile-time, i.e. in module body and similar. In that case it seems you need to explicitly start dependencies:

```elixir
defmodule Foo do
  {:ok, _} = Application.ensure_all_started(:req)
  Req.get(...)
end
```
